Course.create!(
  dept: "cmpt",
  number: "105w",
  term: "fall",
  year: "2024",
  title: "Social Issues and Communication Strategies in Computing Science",
  description: "This course teaches the fundamentals of informative and persuasive communication for professional engineers and computer scientists. A principal goal of this course is to assist students in thinking critically about various contemporary technical, social, and ethical issues. It focuses on communicating technical information clearly and concisely, managing issues of persuasion when communicating with diverse audiences, presentation skills, and teamwork.",
  requisite_description: "",
  prereq_logic: "#no_prereq_logic", # implement
  short_description: "This course teaches the fundamentals of informative and persuasive communication for professional engineers and computer scientists. A principal goal of this course is to assist students in thinking critically about various contemporary technical, social, and ethical issues. It focuses on communicating technical information clearly and concisely, managing issues of persuasion when communicating with diverse audiences, presentation skills, and teamwork.",
  credits: 3,
  instructors: [ "Harinder Khangura", "Cristina Eftenaru" ],
  campuses: [ "Surrey", "Burnaby" ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100", "e100" ],
  requisites: [],
)
Course.create!(
  dept: "cmpt",
  number: "120",
  term: "fall",
  year: "2024",
  title: "Introduction to Computing Science and Programming I",
  description: "An elementary introduction to computing science and computer programming, suitable for students with little or no programming background. Students will learn fundamental concepts and terminology of computing science, acquire elementary skills for programming in a high-level language, e.g. Python. The students will be exposed to diverse fields within, and applications of computing science. Topics will include: pseudocode; data types and control structures; fundamental algorithms; recursion; reading and writing files; measuring performance of algorithms; debugging tools; basic terminal navigation using shell commands. Treatment is informal and programming is presented as a problem-solving tool. ",
  requisite_description: "BC Math 12 or equivalent is recommended.",
  prereq_logic: "#no_prereq_logic", # implement
  short_description: "An elementary introduction to computing science and computer programming, suitable for students with little or no programming background. Students will learn fundamental concepts and terminology of computing science, acquire elementary skills for programming in a high-level language, e.g. Python. The students will be exposed to diverse fields within, and applications of computing science. Topics will include: pseudocode; data types and control structures; fundamental algorithms; recursion; reading and writing files; measuring performance of algorithms; debugging tools; basic terminal navigation using shell commands. Treatment is informal and programming is presented as a problem-solving tool. ",
  credits: 3,
  instructors: [ "Toby Donaldson", "Nicholas Vincent", "Brian Fraser" ],
  campuses: [ "Burnaby", "Surrey" ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100", "d300", "d400" ],
  requisites: [],
)
Course.create!(
  dept: "cmpt",
  number: "125",
  term: "fall",
  year: "2024",
  title: "Introduction to Computing Science and Programming II",
  description: "A rigorous introduction to computing science and computer programming, suitable for students who already have some background in computing science and programming.  Intended for students who will major in computing science or a related program. Topics include: memory management; fundamental algorithms; formally analyzing the running time of algorithms; abstract data types and elementary data structures; object-oriented programming and software design; specification and program correctness; reading and writing files; debugging tools; shell commands.",
  requisite_description: "CMPT 120 or CMPT 130, with a minimum grade of C-.",
  prereq_logic: "CMPT 120 >= C- OR CMPT 130 >= C-", # implement
  short_description: "A rigorous introduction to computing science and computer programming, suitable for students who already have some background in computing science and programming.  Intended for students who will major in computing science or a related program. Topics include: memory management; fundamental algorithms; formally analyzing the running time of algorithms; abstract data types and elementary data structures; object-oriented programming and software design; specification and program correctness; reading and writing files; debugging tools; shell commands.",
  credits: 3,
  instructors: [ "Victor Cheung" ],
  campuses: [ "Burnaby" ],
  delivery_methods: [ "In Person" ],
  sections: [ "e100" ],
  requisites: [],
)
Course.create!(
  dept: "cmpt",
  number: "130",
  term: "fall",
  year: "2024",
  title: "Introduction to Computer Programming I",
  description: "An introduction to computing science and computer programming, using a systems oriented language, such as C or C++. This course introduces basic computing science concepts. Topics will include: elementary data types, control structures, functions, arrays and strings, fundamental algorithms, computer organization and memory management.",
  requisite_description: "BC Math 12 (or equivalent, or any of MATH 100, 150, 151, 154, or 157, with a minimum grade of C-).",
  prereq_logic: "MATH 100 >= C- OR MATH 150 >= C- OR MATH 151 >= C- OR MATH 154 >= C- OR MATH 157 >= C-", # implement
  short_description: "An introduction to computing science and computer programming, using a systems oriented language, such as C or C++. This course introduces basic computing science concepts. Topics will include: elementary data types, control structures, functions, arrays and strings, fundamental algorithms, computer organization and memory management.",
  credits: 3,
  instructors: [ "Brian Fraser" ],
  campuses: [ "Surrey" ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100" ],
  requisites: [],
)
Course.create!(
  dept: "cmpt",
  number: "201",
  term: "fall",
  year: "2024",
  title: "Systems Programming",
  description: "An introduction to a UNIX-like application-OS interface from a programmer's perspective. Introduces operating systems and their interfaces for user-level programs. Students learn how to programmatically interact with an OS efficiently, correctly, and securely. Topics include: command-line tools, programming with memory, processes, threads, IPC, as well as basics of OS security.",
  requisite_description: "(CMPT 125 or CMPT 135) and MACM 101, both with a minimum grade of C-.",
  prereq_logic: "(CMPT 125 >= C- OR CMPT 135 >= C-) AND MACM 101 >= C-", # implement
  short_description: "An introduction to a UNIX-like application-OS interface from a programmer's perspective. Introduces operating systems and their interfaces for user-level programs. Students learn how to programmatically interact with an OS efficiently, correctly, and securely. Topics include: command-line tools, programming with memory, processes, threads, IPC, as well as basics of OS security.",
  credits: 4,
  instructors: [ "Steven Ko" ],
  campuses: [ "Burnaby" ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100" ],
  requisites: [],
)
Course.create!(
  dept: "cmpt",
  number: "210",
  term: "fall",
  year: "2024",
  title: "Probability and Computing",
  description: "Probability has become an essential tool in modern computer science with applications in randomized algorithms, computer vision and graphics, systems, data analysis, and machine learning. The course introduces the foundational concepts in probability as required by many modern applications in computing.",
  requisite_description: "MACM 101, MATH 152, CMPT 125 or CMPT 135, and (MATH 240 or MATH 232), all with a minimum grade of C-.",
  prereq_logic: "MACM 101 >= C- AND MATH 152 >= C- AND (CMPT 125 >= C- OR CMPT 135 >= C-) AND (MATH 240 >= C- OR MATH 232 >= C-)", # implement
  short_description: "Probability has become an essential tool in modern computer science with applications in randomized algorithms, computer vision and graphics, systems, data analysis, and machine learning. The course introduces the foundational concepts in probability as required by many modern applications in computing.",
  credits: 3,
  instructors: [ "Sharan Vaswani" ],
  campuses: [ "Burnaby" ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100", "d200" ],
  requisites: [],
)
Course.create!(
  dept: "cmpt",
  number: "213",
  term: "fall",
  year: "2024",
  title: "Object Oriented Design in Java",
  description: "An introduction to object oriented design using Java. The Java programming language is introduced,

with an emphasis on its advanced features. The course covers the building blocks of object oriented

design including inheritance, polymorphism, interfaces and abstract classes. A number of object oriented design patterns are presented, such as observer, iterator, and singleton. The course also teaches best-practices in code construction. It includes a basic introduction to programming event driven graphical user interfaces.",
  requisite_description: "CMPT 225 with a minimum grade of C-.",
  prereq_logic: "CMPT 225 >= C-", # implement
  short_description: "An introduction to object oriented design using Java. The Java programming language is introduced,

with an emphasis on its advanced features. The course covers the building blocks of object oriented

design including inheritance, polymorphism, interfaces and abstract classes. A number of object oriented design patterns are presented, such as observer, iterator, and singleton. The course also teaches best-practices in code construction. It includes a basic introduction to programming event driven graphical user interfaces.",
  credits: 3,
  instructors: [ "Brian Fraser" ],
  campuses: [ "Surrey" ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100" ],
  requisites: [],
)
Course.create!(
  dept: "cmpt",
  number: "225",
  term: "fall",
  year: "2024",
  title: "Data Structures and Programming",
  description: "Introduction to a variety of practical and important data structures and methods for implementation and for experimental and analytical evaluation. Topics include: stacks, queues and lists; search trees; hash tables and algorithms; efficient sorting; object-oriented programming; time and space efficiency analysis; and experimental evaluation. ",
  requisite_description: "(MACM 101 and (CMPT 125, CMPT 129 or CMPT 135)) or (ENSC 251 and ENSC 252), all with a minimum grade of C-.",
  prereq_logic: "(MACM 101 >= C- AND (CMPT 125 >= C- OR CMPT 129 >= C- OR CMPT 135 >= C-)) OR (ENSC 251 >= C- AND ENSC 252 >= C-)", # implement
  short_description: "Introduction to a variety of practical and important data structures and methods for implementation and for experimental and analytical evaluation. Topics include: stacks, queues and lists; search trees; hash tables and algorithms; efficient sorting; object-oriented programming; time and space efficiency analysis; and experimental evaluation. ",
  credits: 3,
  instructors: [ "John Edgar", "David Chou" ],
  campuses: [ "Burnaby", "Surrey" ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100", "d200" ],
  requisites: [],
)
Course.create!(
  dept: "cmpt",
  number: "263",
  term: "fall",
  year: "2024",
  title: "Introduction to Human-Centered Computing",
  description: "Surveys contemporary Human-Computer Interaction (HCI) topics on designing, implementing, and evaluating interactive computer systems from a human-centered perspective. Students will learn important concepts including understanding users, incorporating accountability and responsibility in design, creating accessible and inclusive systems, and evaluating system interfaces with well-established methodologies.",
  requisite_description: "CMPT 125 or CMPT 135, with a minimum grade of C-.",
  prereq_logic: "CMPT 125 >= C- OR CMPT 135 >= C-", # implement
  short_description: "Surveys contemporary Human-Computer Interaction (HCI) topics on designing, implementing, and evaluating interactive computer systems from a human-centered perspective. Students will learn important concepts including understanding users, incorporating accountability and responsibility in design, creating accessible and inclusive systems, and evaluating system interfaces with well-established methodologies.",
  credits: 3,
  instructors: [ "Victor Cheung" ],
  campuses: [ "Burnaby" ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100" ],
  requisites: [],
)
Course.create!(
  dept: "cmpt",
  number: "272",
  term: "fall",
  year: "2024",
  title: "Web I - Client-side Development",
  description: "Introduces students to the fundamentals of client-side web programming. Students will gain experience working with markup languages such as HTML and CSS as well as define dynamic behaviour using JavaScript and TypeScript. Students will be introduced to popular front-end frameworks. The web architecture will be discussed, and web services will be invoked using basic API calls to existing REST APIs.",
  requisite_description: "CMPT 120 or CMPT 130 or CMPT 128, with a minimum grade of C-.",
  prereq_logic: "CMPT 120 >= C- OR CMPT 130 >= C- OR CMPT 128 >= C-", # implement
  short_description: "Introduces students to the fundamentals of client-side web programming. Students will gain experience working with markup languages such as HTML and CSS as well as define dynamic behaviour using JavaScript and TypeScript. Students will be introduced to popular front-end frameworks. The web architecture will be discussed, and web services will be invoked using basic API calls to existing REST APIs.",
  credits: 3,
  instructors: [ "Shervin Shirmohammadi" ],
  campuses: [ "Burnaby" ],
  delivery_methods: [ "In Person" ],
  sections: [ "e100" ],
  requisites: [],
)
Course.create!(
  dept: "cmpt",
  number: "276",
  term: "fall",
  year: "2024",
  title: "Introduction to Software Engineering",
  description: "An overview of various techniques used for software development and software project management. Major tasks and phases in modern software development, including requirements, analysis, documentation, design, implementation, testing,and maintenance. Project management issues are also introduced. Students complete a team project using an iterative development process.",
  requisite_description: "One W course, CMPT 225, (MACM 101 or (ENSC 251 and ENSC 252)) and (MATH 151 or MATH 150), all with a minimum grade of C-. MATH 154 or MATH 157 with at least a B+ may be substituted for MATH 151 or MATH 150.",
  prereq_logic: "W_course >= C- AND CMPT 225 >= C- AND (MACM 101 >= C- OR (ENSC 251 >= C- AND ENSC 252 >= C-)) AND ((MATH 150 >= C- OR MATH 151 >= C-) OR (MATH 154 >= B+ OR MATH 157 >= B+))", # implement
  short_description: "An overview of various techniques used for software development and software project management. Major tasks and phases in modern software development, including requirements, analysis, documentation, design, implementation, testing,and maintenance. Project management issues are also introduced. Students complete a team project using an iterative development process.",
  credits: 3,
  instructors: [ "Saba Alimadadi Jani", "Parsa Rajabi", "Steve Pearce", "Herbert Tsang" ],
  campuses: [ "Burnaby", "Surrey" ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100", "d200", "d300", "d400" ],
  requisites: [],
)
Course.create!(
  dept: "cmpt",
  number: "295",
  term: "fall",
  year: "2024",
  title: "Introduction to Computer Systems",
  description: "The curriculum introduces students to topics in computer architecture that are considered fundamental to an understanding of the digital systems underpinnings of computer systems. ",
  requisite_description: "Either (MACM 101 and (CMPT 125 or CMPT 135)) or (MATH 151 and CMPT 102 for students in an Applied Physics program), all with a minimum grade of C-.",
  prereq_logic: "MACM 101 >= C- OR (CMPT 125 >= C- AND CMPT 135 >= C-) OR (MATH 151 >= C- AND CMPT 102 >= C-)", # implement
  short_description: "The curriculum introduces students to topics in computer architecture that are considered fundamental to an understanding of the digital systems underpinnings of computer systems. ",
  credits: 4,
  instructors: [ "Arrvindh Shriraman" ],
  campuses: [ "Burnaby" ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100" ],
  requisites: [],
)
Course.create!(
  dept: "cmpt",
  number: "307",
  term: "fall",
  year: "2024",
  title: "Data Structures and Algorithms",
  description: "Design and analysis of efficient data structures and algorithms. General techniques for building and analyzing algorithms (greedy, divide & conquer, dynamic programming, network flows). Introduction to NP-completeness.",
  requisite_description: "CMPT 225, (MACM 201 or CMPT 210), (MATH 150 or MATH 151), and (MATH 232 or MATH 240), all with a minimum grade of C-. MATH 154 or MATH 157 with a grade of at least B+ may be substituted for MATH 150 or MATH 151.",
  prereq_logic: "CMPT 225 >= C- AND (MACM 201 >= C- OR CMPT 210 >= C-) AND (MATH 150 >= C- OR MATH 151 >= C- OR MATH 232 >= C- OR MATH 240 >= C-)", # implement
  short_description: "Design and analysis of efficient data structures and algorithms. General techniques for building and analyzing algorithms (greedy, divide & conquer, dynamic programming, network flows). Introduction to NP-completeness.",
  credits: 3,
  instructors: [ "Andrei Bulatov", "David Mitchell" ],
  campuses: [ "Burnaby" ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100", "d200" ],
  requisites: [],
)
Course.create!(
  dept: "cmpt",
  number: "310",
  term: "fall",
  year: "2024",
  title: "Introduction to Artificial Intelligence",
  description: "A survey of modern approaches for artificial intelligence (AI). Provides an introduction to a variety of AI topics and prepares students for upper-level courses. Topics include: problem solving with search; adversarial game playing; probability and Bayesian networks; machine learning; and applications such as robotics, visual computing and natural language.",
  requisite_description: "CMPT 225 and (MACM 101 or (ENSC 251 and ENSC 252)), all with a minimum grade of C-.",
  prereq_logic: "CMPT 225 >= C- AND (MACM 101 >= C- OR (ENSC 251 >= C- AND ENSC 252 >= C-))", # implement
  short_description: "A survey of modern approaches for artificial intelligence (AI). Provides an introduction to a variety of AI topics and prepares students for upper-level courses. Topics include: problem solving with search; adversarial game playing; probability and Bayesian networks; machine learning; and applications such as robotics, visual computing and natural language.",
  credits: 3,
  instructors: [ "Angelica Lim", "Ahmadreza Nezami" ],
  campuses: [ "Burnaby" ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100", "d200" ],
  requisites: [],
)
Course.create!(
  dept: "cmpt",
  number: "318",
  term: "fall",
  year: "2024",
  title: "Special Topics in Computing Science",
  description: "Special topics in computing science at the 300 level. Topics that are of current interest or are not covered in regular curriculum will be offered from time to time depending on availability of faculty and student interest.",
  requisite_description: "CMPT 225 with a minimum grade of C-. Additional prerequisites to be determined by the instructor subject to approval by the undergraduate program chair.",
  prereq_logic: "CMPT 225 >= C-", # implement
  short_description: "Special topics in computing science at the 300 level. Topics that are of current interest or are not covered in regular curriculum will be offered from time to time depending on availability of faculty and student interest.",
  credits: 3,
  instructors: [ "Uwe Glaesser" ],
  campuses: [ "Burnaby" ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100" ],
  requisites: [],
)
Course.create!(
  dept: "cmpt",
  number: "340",
  term: "fall",
  year: "2024",
  title: "Biomedical Computing",
  description: "no description available",
  requisite_description: "no prerequisite",
  prereq_logic: "no prerequisite logic", # implement
  short_description: "no short description",
  credits: nil,
  instructors: [],
  campuses: [],
  delivery_methods: [],
  sections: [],
  requisites: [],
)
Course.create!(
  dept: "cmpt",
  number: "353",
  term: "fall",
  year: "2024",
  title: "Computational Data Science",
  description: "Basic concepts and programming tools for handling and processing data. Includes data acquisition, cleaning data sources, application of machine learning techniques and data analysis techniques, large-scale computation on a computing cluster.",
  requisite_description: "CMPT 225 and (BUS 232, STAT 201, STAT 203, STAT 205, STAT 270, STAT 271, ENSC 280, MSE 210, or SEE 241), with a minimum grade of C-.",
  prereq_logic: "CMPT 225 >= C- AND (BUS 232 >= C- OR STAT 201 >= C- OR STAT 203 >= C- OR STAT 205 >= C- OR STAT 270 >= C- OR STAT 271 >= C- OR ENSC 280 >= C- OR MSE 210 >= C- OR SEE 241 >= C-)", # implement
  short_description: "Basic concepts and programming tools for handling and processing data. Includes data acquisition, cleaning data sources, application of machine learning techniques and data analysis techniques, large-scale computation on a computing cluster.",
  credits: 3,
  instructors: [ "Gregory Baker", "Rob Cameron" ],
  campuses: [ "Burnaby" ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100" ],
  requisites: [],
)
Course.create!(
  dept: "cmpt",
  number: "354",
  term: "fall",
  year: "2024",
  title: "Database Systems I",
  description: "Logical representations of data records. Data models. Studies of some popular file and database systems. Document retrieval. Other related issues such as database administration, data dictionary and security.",
  requisite_description: "CMPT 225 and (MACM 101 or (ENSC 251 and ENSC 252)), all with a minimum grade of C-.",
  prereq_logic: "CMPT 225 >= C- AND (MACM 101 >= C- OR (ENSC 251 >= C- AND ENSC 252 >= C-))", # implement
  short_description: "Logical representations of data records. Data models. Studies of some popular file and database systems. Document retrieval. Other related issues such as database administration, data dictionary and security.",
  credits: 3,
  instructors: [ "Martin Ester" ],
  campuses: [ "Burnaby" ],
  delivery_methods: [ "In Person" ],
  sections: [ "e100" ],
  requisites: [],
)
Course.create!(
  dept: "cmpt",
  number: "361",
  term: "fall",
  year: "2024",
  title: "Introduction to Visual Computing",
  description: "Provides a unified introduction to the fundamentals of computer graphics and computer vision (visual computing). Topics include graphics pipelines, sampling and aliasing, geometric transformations, projection and camera models, meshing, texturing, color theory, image filtering and registration, shading and illumination, raytracing, rasterization, animation, optical flow, and game engines.",
  requisite_description: "CMPT 225 and MATH 232 or 240, all with a minimum grade of C-.",
  prereq_logic: "CMPT 225 >= C- AND (MATH 232 >= C- OR MATH 240 >= C-)", # implement
  short_description: "Provides a unified introduction to the fundamentals of computer graphics and computer vision (visual computing). Topics include graphics pipelines, sampling and aliasing, geometric transformations, projection and camera models, meshing, texturing, color theory, image filtering and registration, shading and illumination, raytracing, rasterization, animation, optical flow, and game engines.",
  credits: 3,
  instructors: [ "Xue Bin Jason Peng", "Yagiz Aksoy" ],
  campuses: [ "Burnaby" ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100" ],
  requisites: [],
)
Course.create!(
  dept: "macm",
  number: "101",
  term: "fall",
  year: "2024",
  title: "Discrete Mathematics I",
  description: "Introduction to graph theory, trees, induction, automata theory, formal reasoning, modular arithmetic.",
  requisite_description: "BC Math 12 (or equivalent), or any of MATH 100, 150, 151, 154, 157.",
  prereq_logic: "BC Math 12 >= C- OR MATH 100 >= C- OR MATH 150 >= C- OR MATH 151 >= C- OR MATH 154 >= C- OR MATH 157 >= C-", # implement
  short_description: "Introduction to graph theory, trees, induction, automata theory, formal reasoning, modular arithmetic.",
  credits: 3,
  instructors: [ "Steve Pearce", "Kay C Wiese", "Harinder Khangura" ],
  campuses: [ "Burnaby", "Surrey" ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100", "d200", "e100" ],
  requisites: [],
)
Course.create!(
  dept: "macm",
  number: "201",
  term: "fall",
  year: "2024",
  title: "Discrete Mathematics II",
  description: "A continuation of MACM 101. Topics covered include graph theory, trees, inclusion-exclusion, generating functions, recurrence relations, and optimization and matching.",
  requisite_description: "MACM 101 or (ENSC 251 and one of MATH 232 or MATH 240).",
  prereq_logic: "MACM 101 >= C- OR (ENSC 251 >= C- AND MATH 232 >= C- OR MATH 240 >= C-)", # implement
  short_description: "A continuation of MACM 101. Topics covered include graph theory, trees, inclusion-exclusion, generating functions, recurrence relations, and optimization and matching.",
  credits: 3,
  instructors: [ "Nils Bruin" ],
  campuses: [ "Burnaby", nil ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100", "op01" ],
  requisites: [],
)
Course.create!(
  dept: "macm",
  number: "204",
  term: "fall",
  year: "2024",
  title: "Computing with Calculus",
  description: "Using a mathematical software package for doing computations from calculus. Development of computer models that analyze and illustrate applications of calculus. All calculations and experiments will be done in the Maple software package. Topics include: graphing functions and data, preparing visual aids for illustrating mathematical concepts, integration, Taylor series, numerical approximation methods, 3D visualization of curves and surfaces, multi-dimensional optimization, differential equations and disease spread models.",
  requisite_description: "One of CMPT 102, 120, 126, 128 or 130 and MATH 251. MATH 251 can be taken as a corequisite. Students in excess of 80 units may not take MACM 204 for further credit.",
  prereq_logic: "CMPT 102 >= C- OR CMPT 120 >= C- OR CMPT 126 >= C- OR CMPT 128 >= C- OR CMPT 130 >= C- AND MATH 251 >= C-", # implement
  short_description: "Using a mathematical software package for doing computations from calculus. Development of computer models that analyze and illustrate applications of calculus. All calculations and experiments will be done in the Maple software package. Topics include: graphing functions and data, preparing visual aids for illustrating mathematical concepts, integration, Taylor series, numerical approximation methods, 3D visualization of curves and surfaces, multi-dimensional optimization, differential equations and disease spread models.",
  credits: 2,
  instructors: [ "Michael Monagan" ],
  campuses: [ "Burnaby" ],
  delivery_methods: [ "In Person" ],
  sections: [ "e100" ],
  requisites: [],
)
Course.create!(
  dept: "macm",
  number: "316",
  term: "fall",
  year: "2024",
  title: "Numerical Analysis I",
  description: "A presentation of the problems commonly arising in numerical analysis and scientific computing and the basic methods for their solutions.",
  requisite_description: "MATH 152 or 155 or 158, and MATH 232 or 240, and computing experience.",
  prereq_logic: "MATH 152 >= C- OR MATH 155 >= C- OR MATH 158 >= C- AND MATH 232 >= C- OR MATH 240 >= C-", # implement
  short_description: "A presentation of the problems commonly arising in numerical analysis and scientific computing and the basic methods for their solutions.",
  credits: 3,
  instructors: [ "Ralf Wittenberg" ],
  campuses: [ "Burnaby" ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100" ],
  requisites: [],
)
Course.create!(
  dept: "macm",
  number: "416",
  term: "fall",
  year: "2024",
  title: "Numerical Analysis II",
  description: "The numerical solution of ordinary differential equations and elliptic, hyperbolic and parabolic partial differential equations will be considered.",
  requisite_description: "(MATH 260 or MATH 310) and MACM 316.",
  prereq_logic: "MATH 260 >= C- OR MATH 310 >= C- AND MACM 316 >= C-", # implement
  short_description: "The numerical solution of ordinary differential equations and elliptic, hyperbolic and parabolic partial differential equations will be considered.",
  credits: 3,
  instructors: [ "Nilima Nigam" ],
  campuses: [ "Burnaby" ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100" ],
  requisites: [],
)
Course.create!(
  dept: "math",
  number: "100",
  term: "fall",
  year: "2024",
  title: "Precalculus",
  description: "Designed to prepare students for first year Calculus courses. Topics include language and notation of mathematics; problem solving; algebraic, exponential, logarithmic and trigonometric functions and their graphs. ",
  requisite_description: "Pre-Calculus 11 or Foundations of Mathematics 11 (or equivalent)
with a grade of at least B or Pre-Calculus 12 (or equivalent), with a grade of at least C and SFU FAN credit, or SFU FAN X99 course with a grade of at least B-, or achieving a satisfactory grade on the Simon Fraser University Quantitative Placement Test. MATH 100 may not be counted towards the mathematics minor, major or honours degree requirements.",
  prereq_logic: "MATH 11 >= B OR MATH 12 >= C AND SFU FAN >= B-", # implement
  short_description: "Designed to prepare students for first year Calculus courses. Topics include language and notation of mathematics; problem solving; algebraic, exponential, logarithmic and trigonometric functions and their graphs. ",
  credits: 3,
  instructors: [ "Tom Archibald", "Vijaykumar Singh" ],
  campuses: [ "Burnaby", "Surrey" ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100", "d400", "op01", "op02" ],
  requisites: [],
)
Course.create!(
  dept: "math",
  number: "130",
  term: "fall",
  year: "2024",
  title: "Geometry for Computer Graphics",
  description: "An introductory course in the application of geometry and linear algebra principles to computer graphical representation.  Vector and matrix algebra, two and three dimensional transformations, homogeneous coordinates, perspective geometry.",
  requisite_description: "Pre-Calculus 12 or Foundations of

Mathematics 12 (or equivalent) with a

grade of at least B, or MATH 100 with a grade of at least C.",
  prereq_logic: "MATH 12 >= B OR MATH 12 >= B AND FOUNDATIONS OF MATH 12 >= B OR FOUNDATIONS OF MATH 12 >= B OR MATH 100 >= C", # implement
  short_description: "An introductory course in the application of geometry and linear algebra principles to computer graphical representation.  Vector and matrix algebra, two and three dimensional transformations, homogeneous coordinates, perspective geometry.",
  credits: 3,
  instructors: [ "Alexander Rutherford" ],
  campuses: [ "Surrey" ],
  delivery_methods: [ "In Person" ],
  sections: [ "d400", "op01" ],
  requisites: [],
)
Course.create!(
  dept: "math",
  number: "150",
  term: "fall",
  year: "2024",
  title: "Calculus I with Review",
  description: "Designed for students specializing in mathematics, physics, chemistry, computing science and engineering. Topics as for Math 151 with a more extensive review of functions, their properties and their graphs. Recommended for students with no previous knowledge of Calculus. In addition to regularly scheduled lectures, students enrolled in this course are encouraged to come for assistance to the Calculus Workshop (Burnaby), or Math Open Lab (Surrey). ",
  requisite_description: "Pre-Calculus 12 (or equivalent) with a grade of at least B+, or MATH 100 with a grade of at least B-, or achieving a satisfactory grade on the Simon Fraser University Calculus Readiness Test.",
  prereq_logic: "MATH 100 >= B- OR Pre-Calculus 12 >= B+", # implement
  short_description: "Designed for students specializing in mathematics, physics, chemistry, computing science and engineering. Topics as for Math 151 with a more extensive review of functions, their properties and their graphs. Recommended for students with no previous knowledge of Calculus. In addition to regularly scheduled lectures, students enrolled in this course are encouraged to come for assistance to the Calculus Workshop (Burnaby), or Math Open Lab (Surrey). ",
  credits: 4,
  instructors: [ "Jamie Mulholland", "MacKenzie Carr", "Natalia Kouzniak" ],
  campuses: [ "Burnaby", "Surrey", nil ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100", "d200", "d400", "op01" ],
  requisites: [],
)
Course.create!(
  dept: "math",
  number: "151",
  term: "fall",
  year: "2024",
  title: "Calculus I",
  description: "Designed for students specializing in mathematics, physics, chemistry, computing science and engineering. Logarithmic and exponential functions, trigonometric functions, inverse functions. Limits, continuity, and derivatives. Techniques of differentiation, including logarithmic and implicit differentiation. The Mean Value Theorem. Applications of differentiation including extrema, curve sketching, Newton's method. Introduction to modeling with differential equations. Polar coordinates, parametric curves. ",
  requisite_description: "Pre-Calculus 12 (or equivalent) with a grade of at least A, or MATH 100 with a grade of at least B, or achieving a satisfactory grade on the Simon Fraser University Calculus Readiness Test.",
  prereq_logic: "MATH 100 >= B OR Pre-Calculus 12 >= A", # implement
  short_description: "Designed for students specializing in mathematics, physics, chemistry, computing science and engineering. Logarithmic and exponential functions, trigonometric functions, inverse functions. Limits, continuity, and derivatives. Techniques of differentiation, including logarithmic and implicit differentiation. The Mean Value Theorem. Applications of differentiation including extrema, curve sketching, Newton's method. Introduction to modeling with differential equations. Polar coordinates, parametric curves. ",
  credits: 3,
  instructors: [ "Jamie Mulholland", "MacKenzie Carr", "Natalia Kouzniak" ],
  campuses: [ "Burnaby", "Surrey" ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100", "d200", "d400", "op01", "op04" ],
  requisites: [],
)
Course.create!(
  dept: "math",
  number: "152",
  term: "fall",
  year: "2024",
  title: "Calculus II",
  description: "Riemann sum, Fundamental Theorem of Calculus, definite, indefinite and improper integrals, approximate integration, integration techniques, applications of integration. First-order separable differential equations and growth models. Sequences and series, series tests, power series, convergence and applications of power series.",
  requisite_description: "MATH 150 or 151, with a minimum grade of C-; or MATH 154 or 157 with a grade of at least B.",
  prereq_logic: "MATH 150 >= C- OR MATH 151 >= C- OR (MATH 154 >= B AND MATH 157 >= B)", # implement
  short_description: "Riemann sum, Fundamental Theorem of Calculus, definite, indefinite and improper integrals, approximate integration, integration techniques, applications of integration. First-order separable differential equations and growth models. Sequences and series, series tests, power series, convergence and applications of power series.",
  credits: 3,
  instructors: [ "Lyn Ge" ],
  campuses: [ "Burnaby", nil ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100", "op01" ],
  requisites: [],
)
Course.create!(
  dept: "math",
  number: "154",
  term: "fall",
  year: "2024",
  title: "Mathematics for the Life Sciences I",
  description: "Designed for students specializing in the life sciences. Topics include: limits, growth rate and the derivative; elementary functions, optimization and approximation methods, and their applications, integration, and differential equations; mathematical models of biological processes and their implementation and analysis using software.",
  requisite_description: "Pre-Calculus 12 (or equivalent) with a grade of at least B, or MATH 100 with a grade of at least C-, or achieving a satisfactory grade on the Simon Fraser University Calculus Readiness Test.",
  prereq_logic: "Pre-Calculus 12 >= B OR MATH 100 >= C-", # implement
  short_description: "Designed for students specializing in the life sciences. Topics include: limits, growth rate and the derivative; elementary functions, optimization and approximation methods, and their applications, integration, and differential equations; mathematical models of biological processes and their implementation and analysis using software.",
  credits: 3,
  instructors: [ "Cedric Chauve", "Ladislav Stacho" ],
  campuses: [ "Burnaby", "Surrey", nil ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100", "d400", "op01", "op02" ],
  requisites: [],
)
Course.create!(
  dept: "math",
  number: "157",
  term: "fall",
  year: "2024",
  title: "Calculus I for the Social Sciences",
  description: "Designed for students specializing in business or the social sciences. Topics include: limits, growth rate and the derivative; logarithmic, exponential and trigonometric functions and their application to business, economics, optimization and approximation methods; introduction to functions of several variables with emphasis on partial derivatives and extrema.",
  requisite_description: "Pre-Calculus 12 (or equivalent) with a grade of at least B, or MATH 100 with a grade of at least C, or achieving a

satisfactory grade on the Simon Fraser University Calculus

Readiness Test.",
  prereq_logic: "#no_prereq_logic", # implement
  short_description: "Designed for students specializing in business or the social sciences. Topics include: limits, growth rate and the derivative; logarithmic, exponential and trigonometric functions and their application to business, economics, optimization and approximation methods; introduction to functions of several variables with emphasis on partial derivatives and extrema.",
  credits: 3,
  instructors: [ "Katrina Honigs", "Tamon Stephen" ],
  campuses: [ "Burnaby", "Surrey", nil ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100", "d400", "op01", "op02" ],
  requisites: [],
)
Course.create!(
  dept: "math",
  number: "190",
  term: "fall",
  year: "2024",
  title: "Principles of Mathematics for Teachers",
  description: "Designed for students pursuing a career as an elementary school teacher. Topics are drawn from number systems as well as plane, solid, and metric geometry. Examination of the historical and cultural development of mathematical ideas and their place in contemporary mathematics. Emphasis on deep understanding of mathematical concepts and on multiple representations: physical, pictorial, and symbolic. Detailed topics include: problem solving, bases, whole and fractional numbers and their arithmetic operations, number theory, ratios, rates, percent, polygons, polyhedra, symmetries, transformations, and measurements.",
  requisite_description: "Pre-Calculus 11 or Foundations of Mathematics 11 (or equivalent)

with a grade of at least B, or SFU FAN X99 course with a grade of at least C, or achieving a satisfactory grade on the Simon Fraser University Quantitative Placement Test. This course may not be counted toward the Mathematics minor, major or honours degree requirements. Students who have taken, have received transfer credit for, or are currently taking MATH 150, 151, 154 or 157 may not take MATH 190 for credit without permission from the Department of Mathematics. Intended to be particularly accessible to students who are not specializing in mathematics.",
  prereq_logic: "MATH 11 >= B OR FAN X99 >= C OR Quantitative Placement Test >= #no_prereq_logic", # implement
  short_description: "Designed for students pursuing a career as an elementary school teacher. Topics are drawn from number systems as well as plane, solid, and metric geometry. Examination of the historical and cultural development of mathematical ideas and their place in contemporary mathematics. Emphasis on deep understanding of mathematical concepts and on multiple representations: physical, pictorial, and symbolic. Detailed topics include: problem solving, bases, whole and fractional numbers and their arithmetic operations, number theory, ratios, rates, percent, polygons, polyhedra, symmetries, transformations, and measurements.",
  credits: 4,
  instructors: [ "Sheena Tan", "Joanna Niezen" ],
  campuses: [ "Burnaby", nil ],
  delivery_methods: [ "Blended", "Online", "In Person" ],
  sections: [ "b100", "ol01", "op01" ],
  requisites: [],
)
Course.create!(
  dept: "math",
  number: "232",
  term: "fall",
  year: "2024",
  title: "Applied Linear Algebra",
  description: "Linear equations, matrices, determinants. Introduction to vector spaces and linear transformations and bases. Complex numbers. Eigenvalues and eigenvectors; diagonalization. Inner products and orthogonality; least squares problems. An emphasis on applications involving matrix and vector calculations.",
  requisite_description: "MATH 150 or 151 or MACM 101, with a minimum grade of C-; or MATH 154 or 157, both with a grade of at least B.",
  prereq_logic: "MATH 150 >= C- OR MATH 151 >= C- OR MACM 101 >= C- OR MATH 154 >= B- OR MATH 157 >= B- AND CGPA >= 2.00", # implement
  short_description: "Linear equations, matrices, determinants. Introduction to vector spaces and linear transformations and bases. Complex numbers. Eigenvalues and eigenvectors; diagonalization. Inner products and orthogonality; least squares problems. An emphasis on applications involving matrix and vector calculations.",
  credits: 3,
  instructors: [ "Saieed Akbari Feyzaabaadi", "Vijaykumar Singh" ],
  campuses: [ "Burnaby", "Surrey", nil ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100", "d400", "op01", "op02" ],
  requisites: [],
)
Course.create!(
  dept: "math",
  number: "240",
  term: "fall",
  year: "2024",
  title: "Algebra I: Linear Algebra",
  description: "Linear equations, matrices, determinants. Real and abstract vector spaces, subspaces and linear transformations; basis and change of basis. Complex numbers. Eigenvalues and eigenvectors; diagonalization. Inner products and orthogonality; least squares problems. Applications. Subject is presented with an abstract emphasis and includes proofs of the basic theorems.",
  requisite_description: "MATH 150 or 151 or MACM 101, with a minimum grade of C-; or MATH 154 or 157, both with a grade of at least B.",
  prereq_logic: "MATH 150 >= C- OR MATH 151 >= C- OR MACM 101 >= C- OR MATH 154 >= B- OR MATH 157 >= B-", # implement
  short_description: "Linear equations, matrices, determinants. Real and abstract vector spaces, subspaces and linear transformations; basis and change of basis. Complex numbers. Eigenvalues and eigenvectors; diagonalization. Inner products and orthogonality; least squares problems. Applications. Subject is presented with an abstract emphasis and includes proofs of the basic theorems.",
  credits: 3,
  instructors: [ "Michael Monagan" ],
  campuses: [ "Burnaby" ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100", "op01" ],
  requisites: [],
)
Course.create!(
  dept: "math",
  number: "251",
  term: "fall",
  year: "2024",
  title: "Calculus III",
  description: "Rectangular, cylindrical and spherical coordinates. Vectors, lines, planes, cylinders, quadric surfaces. Vector functions, curves, motion in space. Differential and integral calculus of several variables. Vector fields, line integrals, fundamental theorem for line integrals, Green's theorem.",
  requisite_description: "MATH 152 with a minimum grade of C-; or MATH 155 or MATH 158 with a grade of at least B. Recommended: It is recommended that MATH 240 or 232 be taken before or concurrently with MATH 251.",
  prereq_logic: "MATH 152 >= C- OR (MATH 155 >= B OR MATH 158 >= B)", # implement
  short_description: "Rectangular, cylindrical and spherical coordinates. Vectors, lines, planes, cylinders, quadric surfaces. Vector functions, curves, motion in space. Differential and integral calculus of several variables. Vector fields, line integrals, fundamental theorem for line integrals, Green's theorem.",
  credits: 3,
  instructors: [ "Weiran Sun", "Justin Gray", "Justin Chan" ],
  campuses: [ "Burnaby", "Surrey" ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100", "d200", "d400", "op01", "op02" ],
  requisites: [],
)
Course.create!(
  dept: "math",
  number: "260",
  term: "fall",
  year: "2024",
  title: "Introduction to Ordinary Differential Equations",
  description: "First-order differential equations, second- and higher-order linear equations, series solutions, introduction to Laplace transform, systems and numerical methods, applications in the physical, biological and social sciences.",
  requisite_description: "MATH 152 with a minimum grade of C-; or MATH 155 or 158, with a grade of at least B; MATH 232 or 240, with a minimum grade of C-.",
  prereq_logic: "MATH 152 >= C- OR (MATH 155 >= B OR MATH 158 >= B) OR (MATH 232 >= C- OR MATH 240 >= C-)", # implement
  short_description: "First-order differential equations, second- and higher-order linear equations, series solutions, introduction to Laplace transform, systems and numerical methods, applications in the physical, biological and social sciences.",
  credits: 3,
  instructors: [ "Ahmad Mokhtar", "Justin Chan" ],
  campuses: [ "Burnaby", "Surrey" ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100", "d400" ],
  requisites: [],
)
Course.create!(
  dept: "math",
  number: "292",
  term: "fall",
  year: "2024",
  title: "Selected Topics in Mathematics",
  description: "Topics will vary from term to term depending on faculty availability and student interest.",
  requisite_description: "Prerequisites will be specified according to the particular topic or topics offered.",
  prereq_logic: "#no_prereq_logic", # implement
  short_description: "Topics will vary from term to term depending on faculty availability and student interest.",
  credits: 3,
  instructors: [ "Joanna Niezen" ],
  campuses: [ "Burnaby" ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100" ],
  requisites: [],
)
Course.create!(
  dept: "math",
  number: "303",
  term: "fall",
  year: "2024",
  title: "Mathematical Journeys III",
  description: "A focused exploration of a special topic (varying from term to term) that builds on mathematical ideas from lower division courses and provides further challenges in quantitative and deductive reasoning. Each Journeys course is designed to appeal particularly to mathematics minor students and others with a broad interest in mathematics. Students may repeat this course for further credit under a different topic.",
  requisite_description: "MATH 152 or 155 or 158, and MATH 232 or 240, all with a minimum grade of C-. There may be additional prerequisites depending on the specific course topic.",
  prereq_logic: "MATH 152 >= C- OR MATH 155 >= C- OR MATH 158 >= C- AND MATH 232 >= C- OR MATH 240 >= C-", # implement
  short_description: "A focused exploration of a special topic (varying from term to term) that builds on mathematical ideas from lower division courses and provides further challenges in quantitative and deductive reasoning. Each Journeys course is designed to appeal particularly to mathematics minor students and others with a broad interest in mathematics. Students may repeat this course for further credit under a different topic.",
  credits: 3,
  instructors: [ "John Stockie" ],
  campuses: [ "Burnaby" ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100" ],
  requisites: [],
)
Course.create!(
  dept: "math",
  number: "308",
  term: "fall",
  year: "2024",
  title: "Linear Optimization",
  description: "Linear programming modelling. The simplex method and its variants. Duality theory. Post-optimality analysis. Applications and software. Additional topics may include: game theory, network simplex algorithm, and convex sets.",
  requisite_description: "MATH 150, 151, 154, or 157 and MATH 240 or 232, all with a minimum grade of C-.",
  prereq_logic: "MATH 150 >= C- AND MATH 151 >= C- AND MATH 154 >= C- AND MATH 157 >= C- AND (MATH 240 >= C- OR MATH 232 >= C-)", # implement
  short_description: "Linear programming modelling. The simplex method and its variants. Duality theory. Post-optimality analysis. Applications and software. Additional topics may include: game theory, network simplex algorithm, and convex sets.",
  credits: 3,
  instructors: [ "Luis Goddyn" ],
  campuses: [ "Burnaby" ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100" ],
  requisites: [],
)
Course.create!(
  dept: "math",
  number: "309",
  term: "fall",
  year: "2024",
  title: "Continuous Optimization",
  description: "Theoretical and computational methods for investigating the minimum of a function of several real variables with and without inequality constraints. Applications to operations research, model fitting, and economic theory.",
  requisite_description: "MATH 232 or 240, and 251, all with a minimum grade of C-.",
  prereq_logic: "MATH 232 >= C- OR MATH 240 >= C- AND MATH 251 >= C-", # implement
  short_description: "Theoretical and computational methods for investigating the minimum of a function of several real variables with and without inequality constraints. Applications to operations research, model fitting, and economic theory.",
  credits: 3,
  instructors: [ "Benjamin Adcock" ],
  campuses: [ "Burnaby" ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100" ],
  requisites: [],
)
Course.create!(
  dept: "math",
  number: "322",
  term: "fall",
  year: "2024",
  title: "Complex Variables",
  description: "Functions of a complex variable, differentiability, contour integrals, Cauchy's theorem, Taylor and Laurent expansions, method of residues.",
  requisite_description: "MATH 251 with a minimum grade of C-.",
  prereq_logic: "MATH 251 >= C-", # implement
  short_description: "Functions of a complex variable, differentiability, contour integrals, Cauchy's theorem, Taylor and Laurent expansions, method of residues.",
  credits: 3,
  instructors: [ "David Muraki" ],
  campuses: [ "Burnaby" ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100" ],
  requisites: [],
)
Course.create!(
  dept: "math",
  number: "336",
  term: "fall",
  year: "2024",
  title: "Job Practicum I",
  description: "This is the first term of work experience in a co-operative education program available to mathematics students. Interested students should contact departmental advisors as early in their careers as possible, for proper counselling. Units from this course do not count towards the units required for an SFU degree.",
  requisite_description: "Students must apply to and receive permission from the co-op co-ordinator at least one, preferably two, terms in advance. They will normally be required to have completed 45 units with a GPA of 2.5. This course will be graded on a pass/withdraw basis. A course fee is required.",
  prereq_logic: "#no_prereq_logic", # implement
  short_description: "This is the first term of work experience in a co-operative education program available to mathematics students. Interested students should contact departmental advisors as early in their careers as possible, for proper counselling. Units from this course do not count towards the units required for an SFU degree.",
  credits: 3,
  instructors: [ "Magnus Billings" ],
  campuses: [ nil ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100", "d200", "i100" ],
  requisites: [],
)
Course.create!(
  dept: "math",
  number: "337",
  term: "fall",
  year: "2024",
  title: "Job Practicum II",
  description: "This is the second term of work experience in a co-operative education program available to mathematics students. Units from this course do not count towards the units required for an SFU degree. This course will be graded on a pass/withdraw basis. A course fee is required.",
  requisite_description: "MATH 336 and permission of the co-op co-ordinator; students must apply at least one term in advance.",
  prereq_logic: "#no_prereq_logic", # implement
  short_description: "This is the second term of work experience in a co-operative education program available to mathematics students. Units from this course do not count towards the units required for an SFU degree. This course will be graded on a pass/withdraw basis. A course fee is required.",
  credits: 3,
  instructors: [ "Magnus Billings" ],
  campuses: [ nil ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100", "d200", "i100" ],
  requisites: [],
)
Course.create!(
  dept: "math",
  number: "340",
  term: "fall",
  year: "2024",
  title: "Algebra II: Rings and Fields",
  description: "The integers, fundamental theorem of arithmetic. Equivalence relations, modular arithmetic. Univariate polynomials, unique factorization. Rings and fields. Units, zero divisors, integral domains. Ideals, ring homomorphisms. Quotient rings, the ring isomorphism theorem. Chinese remainder theorem. Euclidean, principal ideal, and unique factorization domains. Field extensions, minimal polynomials. Classification of finite fields.",
  requisite_description: "MATH 240 with a minimum grade of C- or MATH 232 with a grade of at least B.",
  prereq_logic: "MATH 240 >= C- OR MATH 232 >= B", # implement
  short_description: "The integers, fundamental theorem of arithmetic. Equivalence relations, modular arithmetic. Univariate polynomials, unique factorization. Rings and fields. Units, zero divisors, integral domains. Ideals, ring homomorphisms. Quotient rings, the ring isomorphism theorem. Chinese remainder theorem. Euclidean, principal ideal, and unique factorization domains. Field extensions, minimal polynomials. Classification of finite fields.",
  credits: 3,
  instructors: [ "Nathan Ilten" ],
  campuses: [ "Burnaby" ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100" ],
  requisites: [],
)
Course.create!(
  dept: "math",
  number: "343",
  term: "fall",
  year: "2024",
  title: "Applied Discrete Mathematics",
  description: "Structures and algorithms, generating elementary combinatorial objects, counting (integer partitions, set partitions, Catalan families), backtracking algorithms, branch and bound, heuristic search algorithms.",
  requisite_description: "MACM 201 with a minimum grade of C-. Recommended: Knowledge of a programming language.",
  prereq_logic: "MACM 201 >= C-", # implement
  short_description: "Structures and algorithms, generating elementary combinatorial objects, counting (integer partitions, set partitions, Catalan families), backtracking algorithms, branch and bound, heuristic search algorithms.",
  credits: 3,
  instructors: [ "Luis Goddyn" ],
  campuses: [ "Burnaby" ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100" ],
  requisites: [],
)
Course.create!(
  dept: "math",
  number: "345",
  term: "fall",
  year: "2024",
  title: "Introduction to Graph Theory",
  description: "Fundamental concepts, trees and distances, matchings and factors, connectivity and paths, network flows, integral flows.",
  requisite_description: "MACM 201 with a minimum grade of C-.",
  prereq_logic: "MACM 201 >= C-", # implement
  short_description: "Fundamental concepts, trees and distances, matchings and factors, connectivity and paths, network flows, integral flows.",
  credits: 3,
  instructors: [ "Bojan Mohar" ],
  campuses: [ "Burnaby" ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100" ],
  requisites: [],
)
Course.create!(
  dept: "math",
  number: "360",
  term: "fall",
  year: "2024",
  title: "Introduction to Biomathematics",
  description: "Key ideas and mathematical methods used in applications of mathematics to various biological, ecological, physiological, and medical problems. The course derives, interprets, solves and simulates models of biological systems. Topics could include population models, evolution from trait and genetic perspectives and qualitative analysis of ODEs.",
  requisite_description: "MATH 260 with a minimum grade of C- OR MATH 155 with a minimum grade of A-. Strongly Recommended: Experience with a computing platform such as R, MATLAB, or Python.",
  prereq_logic: "MATH 260 >= C- OR MATH 155 >= A-", # implement
  short_description: "Key ideas and mathematical methods used in applications of mathematics to various biological, ecological, physiological, and medical problems. The course derives, interprets, solves and simulates models of biological systems. Topics could include population models, evolution from trait and genetic perspectives and qualitative analysis of ODEs.",
  credits: 3,
  instructors: [ "Ben Ashby" ],
  campuses: [ "Burnaby" ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100" ],
  requisites: [],
)
Course.create!(
  dept: "math",
  number: "408",
  term: "fall",
  year: "2024",
  title: "Discrete Optimization",
  description: "Model building using integer variables, computer solution, relaxations and lower bounds, heuristics and upper bounds, branch and bound algorithms, cutting plane algorithms, valid inequalities and facets, branch and cut algorithms, Lagrangian duality, column generation of algorithms, heuristics algorithms and analysis. ",
  requisite_description: "MATH 308 with a minimum grade of C-.",
  prereq_logic: "MATH 308 >= C-", # implement
  short_description: "Model building using integer variables, computer solution, relaxations and lower bounds, heuristics and upper bounds, branch and bound algorithms, cutting plane algorithms, valid inequalities and facets, branch and cut algorithms, Lagrangian duality, column generation of algorithms, heuristics algorithms and analysis. ",
  credits: 3,
  instructors: [ "Tamon Stephen" ],
  campuses: [ "Surrey" ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100" ],
  requisites: [],
)
Course.create!(
  dept: "math",
  number: "418",
  term: "fall",
  year: "2024",
  title: "Partial Differential Equations",
  description: "First-order linear equations, the method of characteristics. The wave equation. Harmonic functions, the maximum principle, Green's functions. The heat equation. Distributions and transforms. Higher dimensional eigenvalue problems. An introduction to nonlinear equations. Burgers' equation and shock waves.",
  requisite_description: "(MATH 260 or MATH 310) and one of MATH 314, MATH 320, MATH 322, PHYS 384, all with a minimum grade of C-. An alternative to the above prerequisite is both of (MATH 252 or MATH 254) and (MATH 260 or MATH 310), both with grades of at least A-.",
  prereq_logic: "MATH 260 >= C- OR MATH 310 >= C- AND (MATH 314 >= C- OR MATH 320 >= C- OR MATH 322 >= C- OR PHYS 384 >= C-)", # implement
  short_description: "First-order linear equations, the method of characteristics. The wave equation. Harmonic functions, the maximum principle, Green's functions. The heat equation. Distributions and transforms. Higher dimensional eigenvalue problems. An introduction to nonlinear equations. Burgers' equation and shock waves.",
  credits: 3,
  instructors: [ "Weiran Sun" ],
  campuses: [ "Burnaby" ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100" ],
  requisites: [],
)
Course.create!(
  dept: "math",
  number: "436",
  term: "fall",
  year: "2024",
  title: "Job Practicum III",
  description: "This is the third term of work experience in a co-operative education program available to mathematics students. Units from this course do not count towards the units required for an SFU degree. This course will be graded on a pass/withdraw basis. A course fee is required.",
  requisite_description: "MATH 337 and permission of the co-op co-ordinator; students must apply at least one term in advance.",
  prereq_logic: "''", # implement
  short_description: "This is the third term of work experience in a co-operative education program available to mathematics students. Units from this course do not count towards the units required for an SFU degree. This course will be graded on a pass/withdraw basis. A course fee is required.",
  credits: 3,
  instructors: [ "Magnus Billings" ],
  campuses: [ nil ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100", "d200", "i100" ],
  requisites: [],
)
Course.create!(
  dept: "math",
  number: "437",
  term: "fall",
  year: "2024",
  title: "Job Practicum IV",
  description: "This is the fourth term of work experience in a co-operative education program available to mathematics students. Units from this course do not count towards the units required for an SFU degree. This course will be graded on a pass/withdraw basis. A course fee is required.",
  requisite_description: "MATH 436 and permission of the co-op co-ordinator; students must apply at least one term in advance.",
  prereq_logic: "#no_prereq_logic", # implement
  short_description: "This is the fourth term of work experience in a co-operative education program available to mathematics students. Units from this course do not count towards the units required for an SFU degree. This course will be graded on a pass/withdraw basis. A course fee is required.",
  credits: 3,
  instructors: [ "Magnus Billings" ],
  campuses: [ nil ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100", "d200", "i100" ],
  requisites: [],
)
Course.create!(
  dept: "math",
  number: "447",
  term: "fall",
  year: "2024",
  title: "Coding Theory",
  description: "An introduction to the theory and practice of error-correcting codes. Topics will include finite fields, polynomial rings, linear and non-linear codes, BCH codes, convolutional codes, majority logic decoding, weight distribution of codes, and bounds on the size of codes.",
  requisite_description: "MATH 340 or 332, with a minimum grade of C-.",
  prereq_logic: "MATH 340 >= C- OR MATH 332 >= C-", # implement
  short_description: "An introduction to the theory and practice of error-correcting codes. Topics will include finite fields, polynomial rings, linear and non-linear codes, BCH codes, convolutional codes, majority logic decoding, weight distribution of codes, and bounds on the size of codes.",
  credits: 3,
  instructors: [ "Jonathan Jedwab" ],
  campuses: [ "Burnaby" ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100" ],
  requisites: [],
)
Course.create!(
  dept: "math",
  number: "450",
  term: "fall",
  year: "2024",
  title: "Introduction to Topology",
  description: "Point set topology: definition, continuous maps, homeomorphisms, product and quotient topologies, Hausdorff topologies, connectedness, compactness and compactifications. Algebraic topology: paths, homotopies, fundamental group, universal covering spaces.",
  requisite_description: "MATH 242 and MATH 340, with a minimum grade of C-.",
  prereq_logic: "MATH 242 >= C- AND MATH 340 >= C-", # implement
  short_description: "Point set topology: definition, continuous maps, homeomorphisms, product and quotient topologies, Hausdorff topologies, connectedness, compactness and compactifications. Algebraic topology: paths, homotopies, fundamental group, universal covering spaces.",
  credits: 3,
  instructors: [ "Imin Chen" ],
  campuses: [ "Burnaby" ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100" ],
  requisites: [],
)
Course.create!(
  dept: "math",
  number: "480w",
  term: "fall",
  year: "2024",
  title: "The Art and Craft of Problem Solving",
  description: "Designed for students with a strong interest in problem solving and the determination to persevere in seeking solutions to highly challenging mathematical problems. Intended as a preparation for the Putnam Competition, the most challenging and prestigious undergraduate mathematics competition in North America, in which effective presentation of solutions is as important as skill in problem solving. Reviews strategic principles, tactical approaches, and specific technical tools for problem solving, and mathematical problem solving folklore. Emphasis is placed on clarity of exposition and persuasiveness of written argument, and on development of communication skills. Students interested in MATH 480W are encouraged to take the course as soon as they meet the prerequisites, since performance in the Putnam Competition often improves with second and subsequent attempts. ",
  requisite_description: "MACM 201 with a grade of at least B. At least one of MACM 201, MATH 240, MATH 242, MATH 251, MATH 252 with a grade of at least A, or both of MACM 203, MACM 204 with a grade of at least A. Or permission of the instructor.",
  prereq_logic: "MACM 201 >= B+ AND (MACM 201 >= A OR MATH 240 >= A OR MATH 242 >= A OR MATH 251 >= A OR MATH 252 >= A) OR (MACM 203 >= A AND MACM 204 >= A)", # implement
  short_description: "Designed for students with a strong interest in problem solving and the determination to persevere in seeking solutions to highly challenging mathematical problems. Intended as a preparation for the Putnam Competition, the most challenging and prestigious undergraduate mathematics competition in North America, in which effective presentation of solutions is as important as skill in problem solving. Reviews strategic principles, tactical approaches, and specific technical tools for problem solving, and mathematical problem solving folklore. Emphasis is placed on clarity of exposition and persuasiveness of written argument, and on development of communication skills. Students interested in MATH 480W are encouraged to take the course as soon as they meet the prerequisites, since performance in the Putnam Competition often improves with second and subsequent attempts. ",
  credits: 3,
  instructors: [ "Jonathan Jedwab" ],
  campuses: [ "Burnaby" ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100" ],
  requisites: [],
)
Course.create!(
  dept: "math",
  number: "486",
  term: "fall",
  year: "2024",
  title: "Job Practicum V",
  description: "This is an optional fifth term of work experience in a co-operative education program available to mathematics and statistics students. Units from this course do not count towards the units required for an SFU degree. This course may be repeated for additive credit.",
  requisite_description: "MATH 437 and permission of the co-op co-ordinator. Students must apply at least one term in advance.",
  prereq_logic: "CMPT 225 >= C", # implement
  short_description: "This is an optional fifth term of work experience in a co-operative education program available to mathematics and statistics students. Units from this course do not count towards the units required for an SFU degree. This course may be repeated for additive credit.",
  credits: 3,
  instructors: [ "Magnus Billings" ],
  campuses: [ nil ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100", "d200", "i100" ],
  requisites: [],
)
Course.create!(
  dept: "math",
  number: "498",
  term: "fall",
  year: "2024",
  title: "Communication and Research Skills in the Mathematical Sciences",
  description: "Students will develop skills required for mathematical research. This course will focus on communication in both written and oral form. Students will write documents and prepare presentations in a variety of formats for academic and non-academic purposes. The LaTeX document preparation system will be used. Course will be given on a pass/fail basis. ",
  requisite_description: "",
  prereq_logic: "no prerequisite logic", # implement
  short_description: "Students will develop skills required for mathematical research. This course will focus on communication in both written and oral form. Students will write documents and prepare presentations in a variety of formats for academic and non-academic purposes. The LaTeX document preparation system will be used. Course will be given on a pass/fail basis. ",
  credits: 1,
  instructors: [ "Amarpreet Rattan" ],
  campuses: [ "Burnaby" ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100" ],
  requisites: [],
)
Course.create!(
  dept: "math",
  number: "499w",
  term: "fall",
  year: "2024",
  title: "Honours Research Project",
  description: "An honours research project in mathematics is an original presentation of an area or problem in mathematics. A typical project is an original synthesis of knowledge generated from students research experience. A project can contain substantive, original mathematics, but need not. The presentation consists of a written report and an oral presentation both of which must be completed before the end of the exam period. ",
  requisite_description: "18 units of upper division MATH or MACM courses. Must be in an honours program with a GPA of at least 3.0. Corequisite: MATH 498. Students must have an approved project prior to enrollment.",
  prereq_logic: "#no_prereq_logic", # implement
  short_description: "An honours research project in mathematics is an original presentation of an area or problem in mathematics. A typical project is an original synthesis of knowledge generated from students research experience. A project can contain substantive, original mathematics, but need not. The presentation consists of a written report and an oral presentation both of which must be completed before the end of the exam period. ",
  credits: 5,
  instructors: [],
  campuses: [ nil ],
  delivery_methods: [ "In Person" ],
  sections: [ "d100" ],
  requisites: [],
)
