
Course.create!(
  dept: "stat",
  number: "440",
  term: "fall",
  year: "2024",
  title: "Learning from Big Data",
  description: "A data-first discovery of advanced statistical methods. Focus will be on a series of forecasting and prediction competitions, each based on a large real-world dataset. Additionally, practical tools for statistical modeling in real-world environments will be explored. ",
  requisite_description: "90 units including STAT 350 with a minimum grade of C- and one of STAT 341, STAT 260, or CMPT 225, with a minimum grade of C-, or instructor approval. STAT 240 is also recommended.",
  prereq_logic:"STAT 350 >= C- AND (STAT 341 >= C- OR STAT 260 >= C- OR CMPT 225 >= C- OR w_course)",
  short_description: "A data-first discovery of advanced statistical methods. Focus will be on a series of forecasting and prediction competitions, each based on a large real-world dataset. Additionally, practical tools for statistical modeling in real-world environments will be explored. ",
  credits: 3,
  instructors: ["Lloyd Elliott"],
  campuses: ["Burnaby"],
  delivery_methods: ["In Person"],
  sections: ["d100"],
  requisites: [],
)
Course.create!(
  dept: "stat",
  number: "450",
  term: "fall",
  year: "2024",
  title: "Statistical Theory",
  description: "Distribution theory, methods for constructing tests, estimators, and confidence intervals with special attention to likelihood methods. Properties of the procedures including large sample theory.",
  requisite_description: "STAT 330 with a minimum grade of C-.",
  prereq_logic:"STAT 330 >= C-",
  short_description: "Distribution theory, methods for constructing tests, estimators, and confidence intervals with special attention to likelihood methods. Properties of the procedures including large sample theory.",
  credits: 3,
  instructors: ["Lin Zhang"],
  campuses: ["Burnaby"],
  delivery_methods: ["In Person"],
  sections: ["d100"],
  requisites: [],
)
Course.create!(
  dept: "stat",
  number: "452",
  term: "fall",
  year: "2024",
  title: "Statistical Learning and Prediction",
  description: "An introduction to the essential modern supervised and unsupervised statistical learning methods. Topics include review of linear regression, classification, statistical error measurement, flexible regression and classification methods, clustering and dimension reduction.",
  requisite_description: "STAT 260 and one of STAT 302 or STAT 305 or STAT 350 or ECON 333 or equivalent, with a minimum grade of C-.",
  prereq_logic:"STAT 260 >= C- AND (STAT 302 >= C- OR STAT 305 >= C- OR STAT 350 >= C- OR ECON 333 >= C- OR equivalent)",
  short_description: "An introduction to the essential modern supervised and unsupervised statistical learning methods. Topics include review of linear regression, classification, statistical error measurement, flexible regression and classification methods, clustering and dimension reduction.",
  credits: 3,
  instructors: ["Owen Ward"],
  campuses: ["Burnaby"],
  delivery_methods: ["In Person"],
  sections: ["d100"],
  requisites: [],
)
Course.create!(
  dept: "stat",
  number: "485",
  term: "fall",
  year: "2024",
  title: "Applied Time Series Analysis",
  description: "Introduction to linear time series analysis including moving average, autoregressive and ARIMA models, estimation, data analysis, forecasting errors and confidence intervals, conditional and unconditional models, and seasonal models.",
  requisite_description: "STAT 260 and one of STAT 285 or STAT 302 or STAT 305 or ECON 333 or equivalent, with a minimum grade of C-.",
  prereq_logic:"STAT 260 >= C- AND (STAT 285 >= C- OR STAT 302 >= C- OR STAT 305 >= C- OR ECON 333 >= C-)",
  short_description: "Introduction to linear time series analysis including moving average, autoregressive and ARIMA models, estimation, data analysis, forecasting errors and confidence intervals, conditional and unconditional models, and seasonal models.",
  credits: 3,
  instructors: ["Gary Parker"],
  campuses: ["Burnaby"],
  delivery_methods: ["In Person"],
  sections: ["e100"],
  requisites: [],
)
Course.create!(
  dept: "stat",
  number: "490",
  term: "fall",
  year: "2024",
  title: "Selected Topics in Probability and Statistics",
  description: "Topics in areas of probability and statistics not covered in the regular undergraduate curriculum of the department.",
  requisite_description: "Dependent on the topic covered.",
  prereq_logic:"Please provide the prerequisite sentence, and I'll convert it to a structured logical expression with comparison operators for grades.",
  short_description: "Topics in areas of probability and statistics not covered in the regular undergraduate curriculum of the department.",
  credits: 3,
  instructors: ["Jean-Francois Begin"],
  campuses: ["Burnaby"],
  delivery_methods: ["In Person"],
  sections: ["d100"],
  requisites: [],
)
Course.create!(
  dept: "stat",
  number: "495",
  term: "fall",
  year: "2024",
  title: "Directed Studies in Probability and Statistics",
  description: "Independent reading or research on consultation with the supervising instructor. This course can be repeated for credit.",
  requisite_description: "Written permission of the department undergraduate studies committee.",
  prereq_logic:"#no_prereq_logic",
  short_description: "Independent reading or research on consultation with the supervising instructor. This course can be repeated for credit.",
  credits: 3,
  instructors: ["Joan Hu"],
  campuses: [nil],
  delivery_methods: ["In Person"],
  sections: ["d100"],
  requisites: [],
)
